use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // `SLINT_GALLERY_ONLY` keeps a development build small. Each page is a
    // separate component type in one generated tree, so compiling all 76 pages
    // produces a ~97 MB Rust file and a rustc that peaks near 13 GiB. Naming the
    // pages under work cuts both to a fraction of that. Unset means every page,
    // which is what the release gallery and the website ship.
    println!("cargo:rerun-if-env-changed=SLINT_GALLERY_ONLY");
    let catalog_path = manifest_dir.join("ui/gallery-catalog.slint");
    let catalog = render_catalog(
        &manifest_dir.join("ui/examples"),
        &selected_slugs(),
    );
    match fs::read_to_string(&catalog_path) {
        Ok(current) if current == catalog => {}
        _ => fs::write(&catalog_path, catalog).expect("write gallery catalog"),
    }
    slint_build::compile(manifest_dir.join("ui/gallery.slint"))
        .expect("Slint gallery should compile");
}

/// The pages `SLINT_GALLERY_ONLY` selects, or every page when it is unset, empty
/// or `all`. An unknown slug is reported and ignored, so a typo shows up as a
/// missing gallery branch rather than a silent full build.
fn selected_slugs() -> Vec<String> {
    let Ok(value) = std::env::var("SLINT_GALLERY_ONLY") else {
        return Vec::new();
    };
    if value.trim().is_empty() {
        return Vec::new();
    }
    value
        .split(',')
        .map(str::trim)
        .filter(|slug| !slug.is_empty() && *slug != "all")
        .map(str::to_owned)
        .collect()
}

struct Page {
    slug: String,
    name: String,
}

/// Slint components are distinct types, so the gallery cannot loop over pages.
/// The example directory is the list: every `*Example` export becomes one branch.
fn render_catalog(examples: &Path, only: &[String]) -> String {
    let mut pages = Vec::new();
    for entry in fs::read_dir(examples).expect("read ui/examples") {
        let path = entry.expect("read example entry").path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("slint") {
            continue;
        }
        let source = fs::read_to_string(&path).expect("read example");
        let Some(name) = exported_example(&source) else {
            continue;
        };
        let slug = path
            .file_stem()
            .expect("example file name")
            .to_string_lossy()
            .into_owned();
        if !only.is_empty() && !only.iter().any(|wanted| wanted == &slug) {
            continue;
        }
        pages.push(Page { slug, name });
    }
    pages.sort_by(|a, b| a.slug.cmp(&b.slug));

    for slug in only {
        if !pages.iter().any(|page| &page.slug == slug) {
            println!("cargo:warning=SLINT_GALLERY_ONLY names no example: {slug}");
        }
    }

    let mut out = String::from(
        "// Generated by build.rs from ui/examples/*.slint. Do not edit.\n\
         // Each page is a separate component type, so the gallery selects it\n\
         // with one branch. Adding an example file adds the branch.\n",
    );
    if !only.is_empty() {
        out.push_str(&format!(
            "// SLINT_GALLERY_ONLY is set, so this is a development build with\n\
             // {} of the pages.\n",
            pages.len()
        ));
    }
    out.push('\n');
    for page in &pages {
        out.push_str(&format!(
            "import {{ {name} }} from \"examples/{slug}.slint\";\n",
            name = page.name,
            slug = page.slug,
        ));
    }
    out.push_str(
        "\nexport component GalleryCatalog inherits VerticalLayout {\n    \
         in property <string> component;\n\
         \n    \
         // No `alignment: start`. It aligns along the main axis, so every\n    \
         // example would keep its preferred height and leave the surplus at the\n    \
         // bottom, and a finished screen could never fill the frame however it\n    \
         // stretched. The tours are unaffected: each of their children sets an\n    \
         // explicit height, so none of them claims the free space.\n\n",
    );
    for page in &pages {
        out.push_str(&format!(
            "    if component == \"{slug}\": {name} {{ }}\n",
            slug = page.slug,
            name = page.name,
        ));
    }
    out.push_str("}\n");
    out
}

fn exported_example(source: &str) -> Option<String> {
    for line in source.lines() {
        let Some(rest) = line.trim().strip_prefix("export component ") else {
            continue;
        };
        let name = rest.split_whitespace().next().unwrap_or("");
        if name.ends_with("Example") {
            return Some(name.to_string());
        }
    }
    None
}
