import { readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface RegistryTotals {
  /** Component sources the registry ships, summed over every framework. */
  components: number;
  /** How many frameworks have any components to ship. */
  frameworks: number;
}

/**
 * What the registry carries, counted at build time so a figure quoted in the
 * hero stays true as frameworks and components are added — rather than a
 * number someone has to remember to update.
 *
 * `registry/components.json` is generated by `registry/build-manifest.mjs` and
 * sits beside the site, so it is read from disk the way the sidebar and the
 * example counts read their sources.
 */
export function registryTotals(): RegistryTotals {
  try {
    const file = join(process.cwd(), '..', 'registry', 'components.json');
    const registry = JSON.parse(readFileSync(file, 'utf8')) as Record<
      string,
      { components?: Record<string, unknown> | unknown[] }
    >;

    let components = 0;
    let frameworks = 0;
    for (const entry of Object.values(registry)) {
      const names = Array.isArray(entry?.components)
        ? entry.components
        : Object.keys(entry?.components ?? {});
      if (names.length > 0) frameworks += 1;
      components += names.length;
    }
    return { components, frameworks };
  } catch {
    // A missing registry is not worth a broken hero: the page says nothing.
    return { components: 0, frameworks: 0 };
  }
}
